### ISSUE TITLE
下载进度不准确的问题

### ISSUE THREAD

**Issue by wstcyx** [CodeisSunShine/GAPlayer#12]
我替换了demo中的 MP4地址，发现下载时候进度不准确。MP4地址：http://xunlei.jingpin88.com/20171028/i6KBFDlH/mp4/i6KBFDlH.mp4

**Comment by wstcyx** [comment]
![48F93A30-1414-4F34-AEF0-65F7B19CE6A6](https://user-images.githubusercontent.com/14196041/62519405-10cfc800-b85e-11e9-9027-a2b9254ca4a4.png)

**Comment by wstcyx** [comment]
使用demo的MP4地址也会出现   进度不对的情况

**Comment by CodeisSunShine** [comment]
非常抱歉现在才进行恢复，现在已经修复这个bug了。
