### ISSUE TITLE
退出下载列表后再次进入下载状态不准确

### ISSUE THREAD

**Issue by ZL335408** [CodeisSunShine/GAPlayer#6]
退出下载列表后再次进入，全部下载任务都进入的暂停状态可是之前下载的任务还在后台执行中。获取到的下载状态不准确，这块请问怎么处理

**Comment by ZL335408** [comment]
关于m3u8文件格式的下载器真的很少，希望能够继续完善支持。

**Comment by CodeisSunShine** [comment]
这段时间在换工作，现在稳定了，之后会持续迭代的，感谢支持。

**Comment by CodeisSunShine** [comment]
现在已经修复了
