### ISSUE TITLE
m3u8不能在後台下載嗎？

### ISSUE THREAD

**Issue by currymax** [CodeisSunShine/GAPlayer#8]
m3u8的下載，app切到後台就不下載了，有什麼辦法解決？

**Comment by CodeisSunShine** [comment]
使用DownloadTask进行后台下载的话，每下载完成一个任务，下一个任务会在2的n-1次方秒后执行下载任务，而m3u8是由若干个ts组成，所以想要实现后台下载的化，个人建议后台播放无声MP3进行保活，或者将m3u8进行压缩成一个任务。
